### ISSUE TITLE
$frandroid --> même élément dans la liste un vingtaine de fois

### ISSUE THREAD

**Issue by davidgeslin** [alizarion/crossview-issues#5]
J'ai sauvegardé une "query" $frandroid.com.
Dans l'onglet "en vrac", je clique sur "frandroid.com", l'article "Bon plan: le samsung ....." compose les 20 premiers éléments de la liste.

**Comment by alizarion** [comment]
lié à un bug serveur du 06/12/2015 corrigé, mais les articles de cette date resteront en doublon
